### ISSUE TITLE
Add parentUid for creating folders

### ISSUE THREAD

**Issue by dexoid** [ZPascal/grafana_api_sdk#103]
Hello.
There is no way to create subfolder using this SDK. But according to official Grafana api documentation additional field for creating subfolders: parentUid.
https://grafana.com/docs/grafana/latest/developers/http_api/folder/#create-folder
Could you add it to grafana-api-sdk?
Thank you!

**Comment by ZPascal** [comment]
@dexoid Yes, I'll add it by the end of the week.

**Comment by ZPascal** [comment]
@dexoid This [PR](https://github.com/ZPascal/grafana_api_sdk/pull/105) fix the case and adds the new feature.
