### ISSUE TITLE
get_user_teams the case of being a member of zero teams

### ISSUE THREAD

**Issue by roman1900** [ZPascal/grafana_api_sdk#110]
I'm wondering if get_user_teams of class User should **not** throw an exception on an empty list as below.
```
if api_call == list() or api_call[0].get("id") is None:
                logging.error(f"Check the error: {api_call}.")
                raise Exception 
```
A user being a member of zero teams seems like a valid outcome to me?

**Comment by ZPascal** [comment]
Hi @roman1900, thank you for reporting the issue. This is a valid result and I have prepared a [Fix](https://github.com/ZPascal/grafana_api_sdk/pull/114) for it.
