### ISSUE TITLE
Unable to Authenticate with HTTPS Grafana host with `APIModel()`

### ISSUE THREAD

**Issue by mikewu-tl** [ZPascal/grafana_api_sdk#26]
Slight change from example:
```
import json

from grafana_api.model import APIModel
from grafana_api.dashboard import Dashboard

model: APIModel = APIModel(
    host="https://www.my-grafana-site.com", 
    token="my-api-token"    
    )

dashboard: Dashboard = Dashboard(model)
dashboard.get_dashboard_by_uid(uid="abcd-efgh")
```

And the error is:
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    dashboard.get_dashboard_by_uid(uid="...")
  File "/Users/.../site-packages/grafana_api/dashboard.py", line 133, in get_dashboard_by_uid
    if api_call.get("dashboard") is None:
AttributeError: 'HTTPResponse' object has no attribute 'get'
```
Do I have to provide a value for `ssl_context` for HTTPS host? What value would that be? I didn't find any info from docs I'm afraid.

**Comment by ZPascal** [comment]
Hi @mikewu-tl, are you using the latest version of the `grafana-api-sdk` ? 

>Was the code I provided using Bearer API token correct? Please let me know what I can look into to pull the list of folders.

The way you handled it looks too good for me. Could you please describe the way you created the API token/service account? What access rights did you use? My current guess is that the uid is not matched/correctly passed or there is an issue with the token. Do you use a self-signed certificate for the Grafana instances?

The case you just tried should actually work as expected and is being tested [here](https://github.com/ZPascal/grafana_api_sdk/blob/6b9ad5761cc3c16ec497eaea8ddff78706a21822/tests/integrationtest/test_dashboard.py#L54) in an integration test.

>For context, I'm trying to programmatically scrape all dashboards from all folders as json, and import them into a newer Grafana host (9.5+).

I've got a similar case to back up the dashboards from one system and move it to another Grafana system.

**Comment by ZPascal** [comment]
Hi @mikewu-tl 
> thanks for looking into this. 
No, problem.

> After some tinkering I finally found out this:
the Grafana HTTP API and the request library only supports http/1.1, which means, for companies that self host Grafana on public cloud (most commonly behind a load balancer) often has http/2 for the endpoint, which is unsupported. In Python, httpx would be more suitable for this.

Thank you for the update. That explains the case. In general, why should I not support http/2? Feel free to open a feature request!
 
> In addition, community discussion (https://community.grafana.com/t/export-dashboard-for-external-use-via-http-api/50716) indicates that there is no programmatic way to fetch exportable JSON, but only in UI.

I'm currently using the SDK to export dashboards and forward them to another directory inside the same Grafana instance. From my understanding, it should be possible to create the exportable JSON.

**Comment by ZPascal** [comment]
I'll close this case and further document the new feature request (`HTTP/2 support`) inside this #33 issue.

**Comment by ZPascal** [comment]
Hi @mikewu-tl, FYI I've implemented HTTP/2 support for the Grafana API SDK.
