### ISSUE TITLE
Why another API package ?

### ISSUE THREAD

**Issue by varac** [ZPascal/grafana_api_sdk#6]
I'm wondering whether I should use this Grafana API project or https://pypi.org/project/grafana-client/, which has a longer history.
What's the reason you decided against using grafana-client and started this ? Just trying to understand, and it would be great to document the differences/reason in the README.md

**Comment by ZPascal** [comment]
Hi @varac, the [grafana-client](https://github.com/panodata/grafana-client) is only a fork of the non-maintained [grafana_api](https://github.com/m0nhawk/grafana_api) repository. In general, the grafana-client project started at the [same time](https://github.com/panodata/grafana-client/commit/43dc65fb66c3231abffacf5d10a0de2974b7c83a), as I started this project. The corresponding SDK is a completely new project and based on non-other project and include a few features that are currently not implemented inside the grafana-client.

The main feature that is implemented inside this library:
- Grafana V8 Alerting API support (possibility to communicate (currently read only) with the attached Prometheus and Alertmanager)

So in general my focus inside this project is to implement and deliver old and new features from the Grafana API, to document all features and functionality clear and to increase the overall test coverage of the project. -> The [grafana_api_sdk](https://github.com/ZPascal/grafana_api_sdk) includes also an integration test (not all features [No Grafana Enterprise instance available]).

**Timeline:**
I am currently implementing about 2 API endpoints every two weeks and would like to keep up this pace in the future. 

Thank you for the hint, I'll update the README.md to make it clear what's the differences between the two libraries. 

If you got further questions, feel free to ask them!

**Comment by ZPascal** [comment]
I've [updated](https://github.com/ZPascal/grafana_api_sdk/pull/7) the documentation. Do you need further information? Otherwise, I'll close the issue in a few days.

**Comment by varac** [comment]
Great, that's very helpful !
